name: Build ibaal3105

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ibaal3105

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Xcode version
        run: xcodebuild -version

      - name: List Xcode project
        run: |
          xcodebuild \
            -list \
            -project ThreeOneOSFive.xcodeproj

      - name: Build
        run: |
          xcodebuild \
            -project ThreeOneOSFive.xcodeproj \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            build
